Updated admin group1 config

diff --git a/.github/workflows/workspace-onboarding.yml b/.github/workflows/workspace-onboarding.yml
--- a/.github/workflows/workspace-onboarding.yml
+++ b/.github/workflows/workspace-onboarding.yml
@@ -215,107 +215,107 @@ jobs:
           outputs: |-
             config: ${{ steps.tfe-configversion.outputs.configuration_version_id}}
 
-  # ## Read matrix outputs - using artifacts until github supports dynamic matric outputs
-  # rmatrix:
-  #   runs-on: ubuntu-latest
-  #   needs: [tfe-ws-cfg-grp]
-  #   steps:
-  #     - uses: cloudposse/github-action-matrix-outputs-read@main
-  #       id: readmatrix
-  #       with:
-  #         matrix-step-name: "tfe-ws-cfg-grp"
-  #   outputs:
-  #     result: "${{ steps.readmatrix.outputs.result }}"
+  ## Read matrix outputs - using artifacts until github supports dynamic matric outputs
+  rmatrix:
+    runs-on: ubuntu-latest
+    needs: [tfe-ws-cfg-grp]
+    steps:
+      - uses: cloudposse/github-action-matrix-outputs-read@main
+        id: readmatrix
+        with:
+          matrix-step-name: "tfe-ws-cfg-grp"
+    outputs:
+      result: "${{ steps.readmatrix.outputs.result }}"
 
       
-  # tfe-ws-run:
-  #   needs: [rmatrix,parse-ws-config]
-  #   runs-on: ubuntu-latest
-  #   strategy:
-  #     max-parallel: 15
-  #     matrix: 
-  #       workspaces: ${{fromJson(needs.parse-ws-config.outputs.admin_workspaces)}}
-  #   steps:
-  #     - name: tfe-config-version
-  #       id: configversion
-  #       env:
-  #         OUTPUT1: ${{ needs.rmatrix.outputs.result }}
-  #       run: | 
-  #         export CONFIG_VERSION=$(echo '${{ needs.rmatrix.outputs.result }}' | jq -r '.config."${{ matrix.workspaces }}"')
-  #         echo "configversion=$CONFIG_VERSION" >> $GITHUB_OUTPUT
-  #     - name: echo config_version
-  #       run: |
-  #         echo "${{steps.configversion.outputs.configversion}}"
-  #     - name: checkout-repo
-  #       uses: actions/checkout@v3
-  #       id: checkout
+  tfe-ws-run:
+    needs: [rmatrix,parse-ws-config]
+    runs-on: ubuntu-latest
+    strategy:
+      max-parallel: 15
+      matrix: 
+        workspaces: ${{fromJson(needs.parse-ws-config.outputs.admin_workspaces)}}
+    steps:
+      - name: tfe-config-version
+        id: configversion
+        env:
+          OUTPUT1: ${{ needs.rmatrix.outputs.result }}
+        run: | 
+          export CONFIG_VERSION=$(echo '${{ needs.rmatrix.outputs.result }}' | jq -r '.config."${{ matrix.workspaces }}"')
+          echo "configversion=$CONFIG_VERSION" >> $GITHUB_OUTPUT
+      - name: echo config_version
+        run: |
+          echo "${{steps.configversion.outputs.configversion}}"
+      - name: checkout-repo
+        uses: actions/checkout@v3
+        id: checkout
 
-  #     - name: Run Terraform Plan
-  #       uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
-  #       continue-on-error: true
-  #       id: run-plan
-  #       with:
-  #         workspace: ${{ matrix.workspaces }}
-  #         configuration_version: ${{ steps.configversion.outputs.configversion }}
+      - name: Run Terraform Plan
+        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
+        continue-on-error: true
+        id: run-plan
+        with:
+          workspace: ${{ matrix.workspaces }}
+          configuration_version: ${{ steps.configversion.outputs.configversion }}
 
-  #     - name: Log Error
-  #       if: ${{ steps.run-plan.outputs.plan_status != 'finished' }} 
-  #       run: |
-  #         echo 'An error occurred in the previous step.'
-  #         echo 'The error message was: ${{ steps.run-plan.outcome }}'
-  #         echo 'run_status: ${{ steps.run-plan.outputs.run_status }}'
-  #         echo 'plan_status: ${{ steps.run-plan.outputs.plan_status }}'
-  #         echo 'payload: ${{ steps.run-plan.outputs.payload }}'
+      - name: Log Error
+        if: ${{ steps.run-plan.outputs.plan_status != 'finished' }} 
+        run: |
+          echo 'An error occurred in the previous step.'
+          echo 'The error message was: ${{ steps.run-plan.outcome }}'
+          echo 'run_status: ${{ steps.run-plan.outputs.run_status }}'
+          echo 'plan_status: ${{ steps.run-plan.outputs.plan_status }}'
+          echo 'payload: ${{ steps.run-plan.outputs.payload }}'
         
-  #     - name: Discard Terraform Run
-  #       if: ${{ steps.run-plan.outputs.plan_status != 'finished' }} 
-  #       uses: hashicorp/tfc-workflows-github/actions/discard-run@v1.0.0
-  #       id: discard-run
-  #       with:
-  #         run: ${{ steps.run-plan.outputs.run_id }}
-  #         comment: "Run discarded due to error ${{ steps.run-plan.outputs.plan_status }}"
+      - name: Discard Terraform Run
+        if: ${{ steps.run-plan.outputs.plan_status != 'finished' }} 
+        uses: hashicorp/tfc-workflows-github/actions/discard-run@v1.0.0
+        id: discard-run
+        with:
+          run: ${{ steps.run-plan.outputs.run_id }}
+          comment: "Run discarded due to error ${{ steps.run-plan.outputs.plan_status }}"
       
-  #     - name: Catch Error   
-  #       if: ${{ steps.run-plan.outputs.plan_status != 'finished' }} 
-  #       run: | 
-  #         exit 1
+      - name: Catch Error   
+        if: ${{ steps.run-plan.outputs.plan_status != 'finished' }} 
+        run: | 
+          exit 1
       
-  #     - uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.0.0
-  #       name: Get plan output
-  #       id: plan-output
-  #       with:
-  #         plan: ${{ steps.run-plan.outputs.plan_id }}
+      - uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.0.0
+        name: Get plan output
+        id: plan-output
+        with:
+          plan: ${{ steps.run-plan.outputs.plan_id }}
       
-  #     - name: Reference plan output
-  #       run: |
-  #         echo 'Plan status: ${{ steps.plan-output.outputs.plan_status }}'
-  #         echo 'Resources to Add: ${{ steps.plan-output.outputs.add }}'
-  #         echo 'Resources to Change: ${{ steps.plan-output.outputs.change }}'
-  #         echo 'Resources to Destroy: ${{ steps.plan-output.outputs.destroy }}'
-  #         echo 'plan_id: ${{ steps.plan-output.outputs.plan_id }}'
-  #     - name: Show run output plan
-  #       uses: hashicorp/tfc-workflows-github/actions/show-run@v1.0.0
-  #       id: show-run-plan
-  #       with:
-  #         run: ${{ steps.run-plan.outputs.run_id }}
-  #     - run: |
-  #         echo 'Latest Run Status: ${{ steps.show-run-plan.outputs.run_status }}'
-  #         echo 'payload: ${{ steps.show-run-plan.outputs.payload }}'
-  #         echo 'run_link: ${{ steps.show-run-plan.outputs.run_link }}'
+      - name: Reference plan output
+        run: |
+          echo 'Plan status: ${{ steps.plan-output.outputs.plan_status }}'
+          echo 'Resources to Add: ${{ steps.plan-output.outputs.add }}'
+          echo 'Resources to Change: ${{ steps.plan-output.outputs.change }}'
+          echo 'Resources to Destroy: ${{ steps.plan-output.outputs.destroy }}'
+          echo 'plan_id: ${{ steps.plan-output.outputs.plan_id }}'
+      - name: Show run output plan
+        uses: hashicorp/tfc-workflows-github/actions/show-run@v1.0.0
+        id: show-run-plan
+        with:
+          run: ${{ steps.run-plan.outputs.run_id }}
+      - run: |
+          echo 'Latest Run Status: ${{ steps.show-run-plan.outputs.run_status }}'
+          echo 'payload: ${{ steps.show-run-plan.outputs.payload }}'
+          echo 'run_link: ${{ steps.show-run-plan.outputs.run_link }}'
 
-  #     - name: Run Terraform Apply
-  #       uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
-  #       id: apply
-  #       with:
-  #         run: ${{ steps.run-plan.outputs.run_id }}
-  #         comment: "Confirmed from GitHub Actions CI"
+      - name: Run Terraform Apply
+        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
+        id: apply
+        with:
+          run: ${{ steps.run-plan.outputs.run_id }}
+          comment: "Confirmed from GitHub Actions CI"
 
-  #     - name: Show run output apply
-  #       uses: hashicorp/tfc-workflows-github/actions/show-run@v1.0.0
-  #       id: show-run
-  #       with:
-  #         run: ${{ steps.apply.outputs.run_id }}
-  #     - run: |
-  #         echo 'Latest Run Status: ${{ steps.show-run.outputs.run_status }}'
-  #         echo 'payload: ${{ steps.show-run.outputs.payload }}'
-  #         echo 'run_link: ${{ steps.show-run.outputs.run_link }}'
+      - name: Show run output apply
+        uses: hashicorp/tfc-workflows-github/actions/show-run@v1.0.0
+        id: show-run
+        with:
+          run: ${{ steps.apply.outputs.run_id }}
+      - run: |
+          echo 'Latest Run Status: ${{ steps.show-run.outputs.run_status }}'
+          echo 'payload: ${{ steps.show-run.outputs.payload }}'
+          echo 'run_link: ${{ steps.show-run.outputs.run_link }}'
